Update suc upgrade plans to support split role cluster
rancher/distros-test-framework pull request #195
Opened 2024-11-28 00:41 UTC by mdrahman-suse

#### Proposed Changes ####

#### Types of Changes ####

#### Testing ####

Checklist:
1. If your PR changes anything on or related to Jenkins, run it pointing to your branch to make sure it's okay.

2. Verify code lint; we should not have errors.

3. Update the documentation if needed.

4. Update makefile and docker run if adding new tests.

5. Run your tests at least 4 times with all configurations needed and possible.

6. If needed test with different os types.

#### Linked Issues ####

#### Further Comments ####

2024-11-28 01:59 UTC, brandond requested changes

2024-11-28 01:59 UTC, brandond commented on workloads/amd64/rke2-upgrade-plan.yaml
> -    args: ["prepare", "rke2-server-cp"]
why did you remove the `prepare` bit here? Without this, none of the plans will wait for other plans to finish before upgrading. They will all just upgrade at once.

you need to have `args: ["prepare", "PLAN-TO-WAIT-FOR"]` in order for one plan to wait for another to complete before proceeding.

2024-11-28 01:59 UTC, brandond commented on workloads/amd64/k3s-upgrade-plan.yaml
> -    args: ["prepare", "k3s-server-etcd"]
same question - why did you remove the prepare? We want each of the roles to wait for the previous role's plan to finish before running. agent should wait for etcd, etcd should wait for cp.

It also looks like there are 4 plans here? I would probably have one yaml file for split-role clusters that had 3 plans (cp/etcd/agent) and another for etcd+cp clusters where you only have 2 plans (server/agent).

2024-12-04 00:56 UTC, brandond submitted a review, later dismissed

2024-12-04 18:21 UTC, ShylajaDevadiga submitted a review, later dismissed

2024-12-06 21:51 UTC, aganesh-suse approved these changes
LGTM

2024-12-09 17:15 UTC, fmoral2 approved these changes

2024-12-09 17:37 UTC, ShylajaDevadiga submitted a review, later dismissed

2024-12-11 21:38 UTC, fmoral2 approved these changes

2024-12-12 07:37 UTC, brandond approved these changes

2024-12-12 13:33 UTC, merged